modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPLv3"
issueTrackerURL = "https://github.com/DavidQF555/TowerOfGod/issues"
[[mods]]
modId = "towerofgod"
version = "${file.jarVersion}"
displayName = "Tower of God"
displayURL = "https://github.com/DavidQF555/TowerOfGod"
logoFile = "logo.png"
credits = "Thanks for this mod goes to SIU and his manhwa, Tower of God"
authors = "DavidQF555"
description = 'This mod adds in many features of the Tower of God universe made by SIU. '
[[dependencies.towerofgod]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.towerofgod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
