modLoader="javafml"
loaderVersion="[32,)"
license="GPLv3"
[[mods]]
modId="towerofgod"
version="${file.jarVersion}"
displayName="Tower of God Mod"
displayURL="https://github.com/DavidQF555/TowerOfGod"
logoFile="logo.png"
credits="Thanks for this mod goes to SIU and his manhwa, Tower of God"
authors="DavidQF555"
description='''
This mod adds in many features of the Tower of God universe made by SIU. 
'''