modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/DavidQF555/TowerOfGod/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/DavidQF555/TowerOfGod"
logoFile = "logo.png"
credits = "Thanks for this mod goes to SIU and his manhwa, Tower of God"
authors = "${mod_authors}"
description = "This mod adds in many features of the Tower of God universe made by SIU. "
[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
